import test from 'node:test';
import assert from 'node:assert/strict';
import { runMissionPilot } from '../lib/mission-pilot.js';
import { buildRequiredWorkingPapers, programmeFingerprint, contentFingerprint, FOLDER_MIME, GOOGLE_DOC_MIME } from '../lib/mission-engine.js';

function scenario() {
  const programme='Test BLE TRANSIT - Controle des soldes clients au 31/12/2025.';
  const sop='Controle des soldes clients. Objectif verifier les soldes clients. Risque solde fictif ou errone. Assertion existence et exactitude. Demander la balance agee clients au 31/12/2025.';
  const meta={id:'P',name:'SIMULATION_PROGRAMME_APPROUVE',mimeType:GOOGLE_DOC_MIME,parents:['M'],modifiedTime:'2026-10-06T00:00:00Z'};
  const template={id:'T',name:'Modele WP soldes clients',mimeType:GOOGLE_DOC_MIME,parents:['LIB'],modifiedTime:meta.modifiedTime};
  const templateText='Client : ............\nExercice : ............\nObjectif : soldes clients';
  const files=new Map([meta,template,...['ROOT','LIB','M','D'].map(id=>({id,name:id,mimeType:FOLDER_MIME,parents:id==='ROOT'?[]:[id==='D'?'M':'ROOT']}))].map(f=>[f.id,f]));
  const drive={getMeta:async id=>files.get(id),listChildren:async id=>[...files.values()].filter(f=>f.parents.includes(id)),readText:async id=>({supported:true,truncated:false,text:id==='P'?programme:templateText}),copyFile:async(id,name,parent)=>{const copy={...files.get(id),id:'WP',name,parents:[parent]};files.set('WP',copy);return copy;}};
  const wpInput={mission_id:'SIM-BLE',mission_type:'AUDIT',mission_reference:'SIM-BLE',mission_name:'BLE TRANSIT TEST',client:'BLE TRANSIT',period:'2025',programme_file_id:'P',programme_modified_at:meta.modifiedTime,programme_fingerprint:programmeFingerprint(meta,programme),programme_validated_confirmed:true,template_library_folder_id:'LIB',library_basis:'CONFIGURED',mission_root_folder_id:'M',destination_folder_id:'D',dry_run:false,prefill_headers:false,requirements:[{cycle:'VEN',procedure:'Controle soldes clients',required_wp_type:'Soldes clients',template_file_id:'T',template_modified_at:template.modifiedTime,template_content_fingerprint:contentFingerprint(template,templateText),source_evidence:{excerpt:programme,location:'Programme simulation'}}]};
  const evidenceMeta={id:'E',modifiedTime:meta.modifiedTime,mimeType:'text/plain'};
  const evidenceRead={supported:true,truncated:false,text:'BLE TRANSIT 2025 - balance agee complete et rapprochee'};
  const checks=Object.fromEntries(['client','mission','scope_account','period','completeness','document_nature'].map(k=>[k,'MATCH']));
  const message={messageId:'SIM-REPLY-1',from:'cfo@example.test',to:['manager@example.test'],sentAt:meta.modifiedTime,subject:'Confirmation et balance',bodyText:'Nous confirmons que cette balance concerne BLE TRANSIT 2025.',rawEml:Buffer.from('SIMULATED ORIGINAL EMAIL'),attachments:[{id:'A',name:'balance.txt'}]};
  const input={missionId:'SIM-BLE',programmeValidated:true,mappingReviewed:true,manager:'manager@example.test',clientContact:'cfo@example.test',cycleOwners:['cycle@example.test'],references:{'Balance agee':'PBC-04-01'},pbcInput:{programmeText:programme,sops:[{file_id:'S',cycle:'VEN',supported:true,truncated:false,text:sop}],controls:[{name:'Controle soldes clients',cycle:'VEN',programme_excerpt:programme,sop_file_id:'S',sop_excerpt:'Controle des soldes clients.',objective_excerpt:'Objectif verifier les soldes clients.',risk_excerpt:'Risque solde fictif ou errone.',assertion_excerpt:'Assertion existence et exactitude.',documents:[{name:'Balance agee',sop_excerpt:'Demander la balance agee clients au 31/12/2025.',completeness_criteria:'Tous clients, exercice 2025, total rapproche',after_selection:false}]}]},replies:[{message,analysis:{matches:[{attachmentId:'A',reference:'PBC-04-01',missionId:'SIM-BLE',contentChecked:true,rationale:'Client et periode controles'}],evidence:{kind:'CONFIRMATION',excerpt:message.bodyText,rationale:'Confirmation de la periode'}},evaluations:{'PBC-04-01':{proposed:'VERIFIED',checks,rationale:'Contenu simule controle integralement et rapproche.',analysedModifiedTime:evidenceMeta.modifiedTime,analysedFingerprint:contentFingerprint(evidenceMeta,evidenceRead.text)}}}]};
  const missions=new Set(),sent=new Map(),archives=new Map(),pbc=new Map();
  const sandbox={simulation:true,initializeMissionOnce:async id=>missions.add(id),prepareWorkingPapers:()=>buildRequiredWorkingPapers(drive,wpInput,{configuredLibraryId:'LIB'}),upsertPbc:async(ref,request)=>{if(!pbc.has(ref))pbc.set(ref,{request,status:'REQUESTED'});},sendEmailOnce:async(key,email)=>{if(!sent.has(key))sent.set(key,email);},getAttachmentBytes:async()=>Buffer.from(evidenceRead.text),storeEvidenceOnce:async(key,data)=>{if(!archives.has(key))archives.set(key,data);},readSavedEvidence:async()=>({meta:evidenceMeta,read:evidenceRead}),updatePbcStatus:async(ref,state)=>{pbc.get(ref).status=state.final_state;},dashboard:async()=>({missions:missions.size,workingPapers:files.has('WP')?1:0,sent:sent.size,archives:archives.size,pbc:[...pbc.values()].map(r=>r.status)})};
  return {input,sandbox,archives};
}
test('programme -> SOP -> WP -> PBC -> approval -> reply -> PDF -> status, twice without duplicates',async()=>{const {input,sandbox,archives}=scenario();const draft=await runMissionPilot(input,sandbox);assert.equal(draft.status,'MANAGER_APPROVAL_REQUIRED');assert.equal((await sandbox.dashboard()).sent,0);input.managerApproval={approvedBy:input.manager,fingerprint:draft.fingerprint};const first=await runMissionPilot(input,sandbox);assert.equal(first.status,'SIMULATION_COMPLETED');assert.deepEqual(first.dashboard.pbc,['VERIFIED']);assert.equal([...archives.values()][0].files.length,3);const second=await runMissionPilot(input,sandbox);assert.deepEqual(second.dashboard,first.dashboard);assert.equal(second.remoteWrites,0);});
test('approval cannot authorise a changed recipient',async()=>{const {input,sandbox}=scenario();const draft=await runMissionPilot(input,sandbox);input.managerApproval={approvedBy:input.manager,fingerprint:draft.fingerprint};input.clientContact='another@example.test';assert.equal((await runMissionPilot(input,sandbox)).status,'MANAGER_APPROVAL_REQUIRED');assert.equal((await sandbox.dashboard()).sent,0);});
test('partial content never closes PBC',async()=>{const {input,sandbox}=scenario();input.replies[0].evaluations['PBC-04-01'].checks.completeness='PARTIAL';const draft=await runMissionPilot(input,sandbox);input.managerApproval={approvedBy:input.manager,fingerprint:draft.fingerprint};assert.equal((await runMissionPilot(input,sandbox)).processed[0].final_state,'REVIEW');});
test('live execution and unapproved mapping are blocked',async()=>{const {input,sandbox}=scenario();await assert.rejects(runMissionPilot(input,{...sandbox,simulation:false}),/SIMULATION_ONLY/);await assert.rejects(runMissionPilot({...input,mappingReviewed:false},sandbox),/APPROVAL_REQUIRED/);});
