import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {validateTeam,missionReviewAction,getMissionReviews,approvedMissionTeam} from '../lib/mission-reviews.js';import {ROUTES} from '../api/app.js';
const id=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0'),hash='a'.repeat(64);
const body=()=>({mission_id:id(2),plan_id:id(3),plan_hash:hash,expected_team_id:null,members:[{staff_profile_id:id(5),mission_role:'Manager',allocation_pct:25,planned_start:'2026-10-12',planned_end:'2026-10-30'}]});
test('team accepts only explicit roles, allocations, dates and staff references',()=>{assert.equal(validateTeam(body()).p_members[0].allocation_pct,25);for(const mutation of [b=>b.members.push(b.members[0]),b=>b.members[0].allocation_pct=101,b=>b.members[0].planned_start='2026-02-30',b=>b.members[0].full_name='Forged name',b=>delete b.expected_team_id]){const b=body();mutation(b);assert.throws(()=>validateTeam(b),/INVALID_TEAM/);}});
test('team proposal uses restricted RPC and server organisation, without executing staffing',async()=>{const r=await missionReviewAction(id(1),{...body(),action:'save-team',org_id:id(99)},async(path,options)=>{assert.equal(path,'rpc/office_save_mission_team');assert.equal(JSON.parse(options.body).p_org_id,id(1));return[{id:id(7)}];});assert.equal(r.executed,false);});
test('capacity declaration is mandatory for approving team; exact reviewed hash is forwarded',async()=>{const b={action:'decide',mission_id:id(2),target_kind:'team',target_id:id(7),content_hash:hash,decision:'approve',note:'Synthetic',request_id:id(8),expected_decision_id:null,reviewed_team_id:null};await assert.rejects(missionReviewAction(id(1),b),/CAPACITY_REVIEW_REQUIRED/);await missionReviewAction(id(1),{...b,capacity_reviewed:true},async(path,options)=>{const d=JSON.parse(options.body);assert.equal(d.p_content_hash,hash);assert.equal(d.p_capacity_reviewed,true);return[];});});
function fixture(){const state={teamId:id(7),programmeId:id(4),planDecision:'approve',teamDecision:'approve',programmeDecision:'approve',programmeTeam:id(7),active:true};const fetchRows=async path=>{
 assert.match(path,/org_id=eq/);
 if(path.startsWith('office_missions?'))return[{id:id(2),name:'Synthetic',planned_start:'2026-10-12',planned_end:'2026-10-30'}];
 if(path.startsWith('office_mission_plan_versions?'))return[{id:id(3),version:1,content_hash:hash,phases:['Phase']}];
 if(path.startsWith('office_mission_programme_versions?'))return[{id:state.programmeId,plan_id:id(3),version:1,content_hash:'b'.repeat(64),phases:[]}];
 if(path.startsWith('office_mission_plan_decisions?'))return[{decision:state.planDecision}];
 if(path.startsWith('office_mission_team_versions?'))return[{id:state.teamId,plan_id:id(3),version:1,content_hash:'c'.repeat(64),members:body().members}];
 if(path.startsWith('office_staff_profiles?'))return state.active?[{id:id(5),full_name:'Synthetic person'}]:[];
 if(path.startsWith('office_mission_review_decisions?')){if(path.includes('target_kind=eq.team'))return[{id:id(10),decision:state.teamDecision,content_hash:'c'.repeat(64)}];if(path.includes('target_kind=eq.programme'))return[{id:id(11),decision:state.programmeDecision,content_hash:'b'.repeat(64),reviewed_team_id:state.programmeTeam}];return[];}
 throw Error(path);
};return{state,fetchRows};}
test('approved budget team is drawn from reviewed immutable snapshot, not proposed planning rows',async()=>{const {fetchRows}=fixture();const result=await approvedMissionTeam(id(1),id(2),fetchRows);assert.equal(result.team_version_id,id(7));assert.equal(result.assignments[0].status,'validated');assert.equal(result.assignments[0].id,id(5));});
test('new team, rejected plan, inactive staff or unapproved programme prevents budget preparation',async()=>{for(const mode of ['team','plan','staff','programme']){const {state,fetchRows}=fixture();if(mode==='team')state.teamId=id(99);if(mode==='plan')state.planDecision='reject';if(mode==='staff')state.active=false;if(mode==='programme')state.programmeDecision='defer';await assert.rejects(approvedMissionTeam(id(1),id(2),fetchRows),/APPROVAL_REQUIRED/);}});
test('review reads latest decisions separately and owner routes preserve private directory',async()=>{const {fetchRows}=fixture();const r=await getMissionReviews(id(1),id(2),fetchRows);assert.equal(r.programme_approved,true);assert.equal(ROUTES['mission-review'].GET.ownerOnly,true);assert.equal(ROUTES['mission-review'].POST.ownerOnly,true);const script=readFileSync(new URL('../assets/mission-review.js',import.meta.url),'utf8');assert.doesNotMatch(script,/innerHTML/);assert.match(script,/pending.*crypto.randomUUID/);});
