import test from 'node:test';
import assert from 'node:assert/strict';
import ExcelJS from 'exceljs';
import {prepareMissionBudget,missionBudgetAction,buildMissionBudgetWorkbook} from '../lib/mission-budgets.js';
import {createMissionBudgetAction} from '../supabase/functions/taty-google-bridge/mission-budget-files.ts';
import {buildSpecialistTools} from '../lib/agent-tools.js';
import {ROUTES} from '../api/app.js';
const id=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
const source=()=>({mission:{id:id(2),name:'Synthetic mission'},plan_approved:true,plan:{id:id(3),content_hash:'a'.repeat(64)},programmes:[{id:id(4),plan_id:id(3),content_hash:'b'.repeat(64),phases:[{phase_index:0,tasks:[{title:'Synthetic task',procedure:'Synthetic procedure',due_on:'2026-10-20'}]}]}]});
const input=()=>({mission_id:id(2),programme_id:id(4),currency:'XOF',template_file_id:'synthetic_template',destination_parent_id:'synthetic_folder',tasks:[{phase_index:0,task_index:0,allocations:[{assignment_id:id(5),hours:4,hourly_rate:100,rate_source:'Owner-confirmed synthetic rate'}]}]});
function fixture(){const state={source:source(),status:'confirmed',decision:null,budget:null,writes:0};const deps={approvedTeam:async()=>({team_version_id:id(8),team_hash:"d".repeat(64),assignments:[{id:id(5),staff_profile_id:id(6),mission_role:"Synthetic role",status:state.status}]}),getProgramme:async()=>state.source,fetchRows:async(path,opt)=>{
 if(path.startsWith('office_mission_assignments?'))return[{id:id(5),staff_profile_id:id(6),mission_role:'Synthetic role',status:state.status}];
 if(path.startsWith('office_staff_profiles?'))return[{id:id(6),full_name:'Synthetic person'}];
 if(path.startsWith('orpailleur_inventory?'))return[{file_id:'synthetic_folder'}];
 if(path.startsWith('office_mission_budget_versions?')){if(opt?.method==='POST'){state.budget={...JSON.parse(opt.body)[0],id:id(7)};return[state.budget];}return[state.budget];}
 if(path.startsWith('office_mission_budget_decisions')){if(opt?.method==='POST'){state.decision=JSON.parse(opt.body)[0];return[];}return state.decision?[state.decision]:[];}
 throw Error(path);
},mappingGate:async()=>({allowed:true}),driveId:'drive',getMeta:async()=>({mimeType:'application/vnd.google-apps.folder',driveId:'drive'}),createFile:async()=>{state.writes++;return{id:'newfile',name:'synthetic.xlsx'};}};return{state,deps};}
test('budget covers source tasks and resolves names internally, never allocation percentages',async()=>{const {deps}=fixture();const d=await prepareMissionBudget(id(1),input(),deps);assert.equal(d.data.team[0].name,'Synthetic person');assert.equal(d.data.tasks[0].allocations[0].hours,4);assert.equal(d.data.team[0].hourly_rate,100);assert.equal(d.missing_rates.length,0);});
test('budget blocks unapproved plan, unconfirmed team, stale programme and uncovered tasks',async()=>{for(const mode of ['plan','team','programme','tasks']){const {state,deps}=fixture(),body=input();if(mode==='plan')state.source.plan_approved=false;if(mode==='team')state.status='proposed';if(mode==='programme')body.programme_id=id(99);if(mode==='tasks')body.tasks.push(body.tasks[0]);await assert.rejects(prepareMissionBudget(id(1),body,deps));}});
test('unknown rates stay unknown and prevent approval; zero rate requires an explicit source',async()=>{const {deps}=fixture(),body=input();body.tasks[0].allocations[0].hourly_rate=null;body.tasks[0].allocations[0].rate_source='';const d=await missionBudgetAction(id(1),{...body,action:'prepare'},deps);assert.equal(d.missing_rates.length,1);await assert.rejects(missionBudgetAction(id(1),{action:'approve',budget_id:d.budget_id,content_hash:d.content_hash},deps),/CONFIRMED_RATES_REQUIRED/);body.tasks[0].allocations[0].hourly_rate=0;await assert.rejects(prepareMissionBudget(id(1),body,deps),/INVALID_BUDGET_ALLOCATION/);});
test('approval executes nothing; downloads need approval; changed source invalidates it',async()=>{const {state,deps}=fixture();const d=await missionBudgetAction(id(1),{...input(),action:'prepare'},deps),body={budget_id:d.budget_id,content_hash:d.content_hash};await assert.rejects(missionBudgetAction(id(1),{...body,action:'download'},deps),/BUDGET_APPROVAL_REQUIRED/);await missionBudgetAction(id(1),{...body,action:'approve'},deps);assert.equal(state.writes,0);const out=await missionBudgetAction(id(1),{...body,action:'download'},deps);assert.equal(out.written_to_drive,false);assert.equal(Buffer.from(out.base64,'base64').subarray(0,2).toString(),'PK');state.source.programmes[0].content_hash='c'.repeat(64);await assert.rejects(missionBudgetAction(id(1),{...body,action:'publish'},deps),/BUDGET_SOURCE_CHANGED/);assert.equal(state.writes,0);});
test('JSONB key ordering preserves approval hash and rejection prevents subsequent publishing',async()=>{const {state,deps}=fixture();const d=await missionBudgetAction(id(1),{...input(),action:'prepare'},deps);state.budget.data=Object.fromEntries(Object.entries(state.budget.data).reverse());const body={budget_id:d.budget_id,content_hash:d.content_hash};await missionBudgetAction(id(1),{...body,action:'approve'},deps);await missionBudgetAction(id(1),{...body,action:'publish'},deps);assert.equal(state.writes,1);await missionBudgetAction(id(1),{...body,action:'reject'},deps);await assert.rejects(missionBudgetAction(id(1),{...body,action:'publish'},deps),/BUDGET_APPROVAL_REQUIRED/);assert.equal(state.writes,1);});
test('generated workbook has sourced names, cached budget, formulas and blank actuals',async()=>{const {deps}=fixture();const d=await prepareMissionBudget(id(1),input(),deps);const book=new ExcelJS.Workbook();await book.xlsx.load(await buildMissionBudgetWorkbook(d.data));const sheet=book.getWorksheet('Budget Audit');assert.equal(sheet.getCell('C2').value,'Synthetic person');assert.equal(sheet.getCell('G2').value.result,400);assert.equal(sheet.getCell('G2').value.formula,'E2*F2');assert.equal(sheet.getCell('H2').value,null);assert.match(sheet.getCell('I3').value.formula,/COUNT.*<>1/);assert.equal(book.worksheets.length,4);});
test('budget routes restrict names and rates to owner',()=>{assert.equal(ROUTES['mission-budget'].GET.ownerOnly,true);assert.equal(ROUTES['mission-budget'].POST.ownerOnly,true);});
function bridge(){let uploads=0,claimed=false;const body={org_id:id(1),budget_id:id(7),content_hash:'a'.repeat(64),base64:Buffer.from('PKsynthetic').toString('base64')};const name='MISSION_BUDGET_'+id(7)+'.xlsx';const deps={sourcesCurrent:async()=>true,orgId:id(1),driveId:'drive',getBudget:async()=>({office_mission_id:id(2),content_hash:body.content_hash,data:{destination_parent_id:'folder'}}),getDecision:async()=>({decision:'approve',content_hash:body.content_hash}),getMetadata:async id=>id==='folder'?{id,mimeType:'application/vnd.google-apps.folder',driveId:'drive'}:{id,name,mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',driveId:'drive',parents:['folder']},folderLinked:async()=>true,findExact:async()=>[],claimBudget:async()=>{if(claimed)return false;claimed=true;return true;},uploadCreate:async()=>{uploads++;return{id:'newfile'};}};return{body,deps,uploads:()=>uploads};}
test('bridge prevents concurrent duplicate uploads of the same approved budget',async()=>{const f=bridge();const results=await Promise.allSettled([createMissionBudgetAction(f.deps,f.body),createMissionBudgetAction(f.deps,f.body)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(f.uploads(),1);});
test('bridge refuses other tenant, unapproved budget, unlinked folder and failed readback',async()=>{for(const mode of ['tenant','decision','folder','readback']){const f=bridge();if(mode==='tenant')f.body.org_id=id(99);if(mode==='decision')f.deps.getDecision=async()=>({decision:'reject'});if(mode==='folder')f.deps.folderLinked=async()=>false;if(mode==='readback'){const read=f.deps.getMetadata;f.deps.getMetadata=async id=>id==='folder'?read(id):{id,parents:[],driveId:'drive'};}await assert.rejects(createMissionBudgetAction(f.deps,f.body));assert.equal(f.uploads(),mode==='readback'?1:0);}});

test('Mission Controller exposes budget preparation while Orpailleur keeps documentary tools',()=>{const tools=buildSpecialistTools('mission-controller',{orgId:id(1)});assert.ok(tools.some(t=>t.name==='prepare_office_mission_budget'));assert.ok(tools.some(t=>t.name==='read_office_mission_programme'));assert.ok(tools.some(t=>t.name==='read_office_mission_review'));assert.ok(!buildSpecialistTools('orpailleur',{orgId:id(1)}).some(t=>t.name==='prepare_office_mission_budget'));});

test('bridge refuses a budget whose reviewed mission sources are no longer current',async()=>{const f=bridge();f.deps.sourcesCurrent=async()=>false;await assert.rejects(createMissionBudgetAction(f.deps,f.body),/BUDGET_SOURCE_CHANGED/);assert.equal(f.uploads(),0);});
