// Orpailleur memory — OFFICE_MANAGER_MAP.xlsx + OFFICE_MANAGER_REGISTER.xlsx
//
//   MAP the authorised Drive first -> EXPLAIN -> owner VALIDATES ambiguities
//   -> REMEMBER (signed RULES) -> only then ACT.
//
// - MAP (business understanding) holds sheets MAP, RULES, ROLES, STATE.
//   Memory is about ROLES ("folder X is currently the
//   WORKING_PAPER_TEMPLATE_LIBRARY"), never about frozen paths: rows are keyed
//   by file_id and the path is refreshed on every pass.
// - RULES are the owner's memory. A rule is valid only if it carries an HMAC
//   signature made with OWNER_APPROVAL_SECRET, which only the owner endpoint
//   (api/owner.js) holds. The agent cannot create or forge one; a sentence
//   generated by the AI is never an approval.
// - REGISTER (technical memory) has one row per Drive object keyed by file_id,
//   used for differential passes: UNCHANGED / NEW / MODIFIED / RENAMED / MOVED
//   / DELETED_OR_MISSING (after verification, never on first absence).
// - The pass is READ-ONLY on business files: it only reads the Drive and
//   creates/updates the two memory files in place (same file_id every run).
// - Understanding is done by the AI (record_file_understanding). This module
//   never decides a file's business meaning; MAP never replaces reasoning.
//
// Drive adapter used here (in addition to lib/mission-engine.js's):
//   findFilesByExactName(name, parentId) -> [meta]
//   downloadBuffer(id) -> Buffer
//   createBinary({ name, parentId, buffer, mimeType }) -> meta
//   updateBinary(id, { buffer, mimeType }) -> meta

import ExcelJS from "exceljs";
import { createHmac, timingSafeEqual } from "node:crypto";
import {
  DOCX_MIME,
  FOLDER_MIME,
  GOOGLE_DOC_MIME,
  GOOGLE_SHEET_MIME,
  XLSX_MIME,
  contentFingerprint,
  sha256
} from "./mission-engine.js";

export const MEMORY_FILE_NAMES = {
  map: "OFFICE_MANAGER_MAP.xlsx",
  register: "OFFICE_MANAGER_REGISTER.xlsx"
};

// ---------------------------------------------------------------------------
// Semantic roles (ROLES sheet)
// ---------------------------------------------------------------------------

export const SEMANTIC_ROLES = {
  ACTIVE_ENGAGEMENTS: { cardinality: "MULTIPLE", description: "Folders of engagements in progress" },
  CLOSED_ENGAGEMENTS: { cardinality: "MULTIPLE", description: "Folders of closed engagements" },
  SOP_LIBRARY: { cardinality: "SINGLE", description: "Procedures / methodology library" },
  WORKING_PAPER_TEMPLATE_LIBRARY: { cardinality: "SINGLE", description: "Blank work-product (Working Paper) templates", used_by: "mission-controller" },
  PBC_MASTER: { cardinality: "SINGLE", description: "Approved PBC master checklist", used_by: "mission-controller" },
  MISSION_PROGRAMMES: { cardinality: "MULTIPLE", description: "Work programmes / work plans" },
  HR_CV_LIBRARY: { cardinality: "SINGLE", description: "Staff CVs / HR profiles" },
  FINANCE_ADMIN: { cardinality: "MULTIPLE", description: "Billing, collections, administration" },
  ARCHIVES: { cardinality: "MULTIPLE", description: "Archived material" },
  OFFICE_MANAGER_MEMORY: { cardinality: "MULTIPLE", description: "Office Manager AI memory files (system)" },
  OTHER: { cardinality: "MULTIPLE", description: "Anything else" }
};
export const SEMANTIC_ROLE_KEYS = Object.keys(SEMANTIC_ROLES);

// ---------------------------------------------------------------------------
// Exact sheet structures
// ---------------------------------------------------------------------------

export const MAP_COLUMNS = [
  "map_id", "org", "semantic_role", "target_file_id", "target_kind",
  "target_name", "target_path", "canonical_status", "confidence", "rationale",
  "owner_approval_status", "rule_id", "proposed_by", "proposed_at",
  "last_verified_at", "notes"
];
// canonical_status: AI_HYPOTHESIS | OWNER_APPROVED | REJECTED | SUPERSEDED | TARGET_MISSING
// owner_approval_status: PENDING | APPROVED | REJECTED

export const RULES_COLUMNS = [
  "rule_id", "rule_type", "semantic_role", "target_file_id",
  "target_name_at_approval", "approval_source", "approved_by", "approved_at",
  "active", "signature", "notes"
];
// rule_type: CANONICAL_ROLE_ASSIGNMENT | ROLE_REJECTION | MAPPING_REVIEWED

export const ROLES_COLUMNS = [
  "semantic_role", "cardinality", "description", "requires_owner_approval", "used_by"
];

export const STATE_COLUMNS = ["key", "value", "updated_at"];

export const REGISTER_COLUMNS = [
  "file_id", "parent_id", "name", "path", "mime_type", "size", "modified_time",
  "created_time", "md5", "web_url", "is_folder", "first_seen_at", "last_seen_at",
  "last_inspected_at", "content_fingerprint", "read_status", "semantic_role",
  "classification", "client", "mission", "understanding_status",
  "understanding_confidence", "understanding_rationale", "status",
  "change_type", "missing_since", "missing_checks", "last_action",
  "last_action_at"
];
// status (presence): PRESENT | MISSING_PENDING_CHECK | MOVED_OUT_OF_SCOPE | TRASHED | DELETED_OR_MISSING
// understanding_status: PENDING_READ | NEEDS_UNDERSTANDING | UNDERSTOOD | METADATA_ONLY | EXTRACTOR_REQUIRED
// read_status: READ | NOT_READ | EXTRACTOR_REQUIRED | SKIPPED_SYSTEM

export const MAPPING_STATES = {
  FIRST_MAPPING: "FIRST_MAPPING",
  MAPPING_PENDING_REVIEW: "MAPPING_PENDING_REVIEW",
  MAPPING_REVIEWED: "MAPPING_REVIEWED"
};

export const CHANGE_TYPES = ["UNCHANGED", "NEW", "MODIFIED", "RENAMED", "MOVED", "DELETED_OR_MISSING"];

// A missing file is declared DELETED_OR_MISSING only after this many complete
// passes in a row without finding it anywhere (and not found by id).
export const MISSING_CONFIRMATION_PASSES = 2;

const READABLE_MIMES = new Set([GOOGLE_DOC_MIME, GOOGLE_SHEET_MIME, DOCX_MIME, XLSX_MIME, "application/json"]);
const SYSTEM_FILE_PATTERN =
  /(^~\$|^\.ds_store$|^thumbs\.db$|^desktop\.ini$|\.(dll|exe|sys|tmp|temp|cache|lnk|bak|log)$)/i;
const SYSTEM_FOLDER_PATTERN = /^(\.|__macosx$|\$recycle\.bin$|cache$|tmp$|temp$)/i;

// ---------------------------------------------------------------------------
// XLSX (de)serialisation — every cell is stored as text
// ---------------------------------------------------------------------------

function cellText(value) {
  if (value === null || value === undefined) return "";
  if (typeof value === "object") {
    if (value.richText) return value.richText.map(part => part.text).join("");
    if (value.text !== undefined) return String(value.text);
    if (value.result !== undefined) return String(value.result);
    if (value instanceof Date) return value.toISOString();
  }
  return String(value);
}

export async function buildWorkbookBuffer(sheets) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Office Manager AI";
  for (const [name, { columns, rows }] of Object.entries(sheets)) {
    const sheet = workbook.addWorksheet(name);
    sheet.addRow(columns);
    sheet.getRow(1).font = { bold: true };
    for (const row of rows) sheet.addRow(columns.map(column => String(row[column] ?? "")));
  }
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

export async function parseWorkbookBuffer(buffer, schema) {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.load(buffer);
  const out = {};
  for (const [name, columns] of Object.entries(schema)) {
    const sheet = workbook.getWorksheet(name);
    out[name] = [];
    if (!sheet) continue;
    const header = [];
    sheet.getRow(1).eachCell({ includeEmpty: true }, (cell, col) => {
      header[col - 1] = cellText(cell.value).trim();
    });
    sheet.eachRow({ includeEmpty: false }, (row, rowNumber) => {
      if (rowNumber === 1) return;
      const obj = {};
      for (const column of columns) {
        const index = header.indexOf(column);
        obj[column] = index >= 0 ? cellText(row.getCell(index + 1).value) : "";
      }
      if (Object.values(obj).some(v => String(v).trim())) out[name].push(obj);
    });
  }
  return out;
}

const MAP_SCHEMA = { MAP: MAP_COLUMNS, RULES: RULES_COLUMNS, ROLES: ROLES_COLUMNS, STATE: STATE_COLUMNS };
const REGISTER_SCHEMA = { REGISTER: REGISTER_COLUMNS };

// ---------------------------------------------------------------------------
// Memory store: the SAME two files, located by exact name, updated in place
// ---------------------------------------------------------------------------

function rolesCatalog() {
  return SEMANTIC_ROLE_KEYS.map(role => ({
    semantic_role: role,
    cardinality: SEMANTIC_ROLES[role].cardinality,
    description: SEMANTIC_ROLES[role].description,
    requires_owner_approval: SEMANTIC_ROLES[role].cardinality === "SINGLE" ? "true" : "false",
    used_by: SEMANTIC_ROLES[role].used_by || ""
  }));
}

export async function openMemory(drive, { memoryFolderId, org = "" }) {
  const memory = {
    memoryFolderId,
    exists: false,
    map: { fileId: null, modifiedTime: null, sheets: { MAP: [], RULES: [], ROLES: rolesCatalog(), STATE: [] } },
    register: { fileId: null, modifiedTime: null, rows: [] }
  };

  for (const kind of ["map", "register"]) {
    const found = await drive.findFilesByExactName(MEMORY_FILE_NAMES[kind], memoryFolderId);
    if (found.length > 1) {
      // Never create a third file, never pick one arbitrarily.
      throw new Error(`MEMORY_FILE_DUPLICATE: ${found.length} files named ${MEMORY_FILE_NAMES[kind]}`);
    }
    if (!found.length) continue;
    const meta = found[0];
    const buffer = await drive.downloadBuffer(meta.id);
    if (kind === "map") {
      const sheets = await parseWorkbookBuffer(buffer, MAP_SCHEMA);
      memory.map = {
        fileId: meta.id,
        modifiedTime: meta.modifiedTime,
        sheets: { ...sheets, ROLES: sheets.ROLES.length ? sheets.ROLES : rolesCatalog() }
      };
    } else {
      const sheets = await parseWorkbookBuffer(buffer, REGISTER_SCHEMA);
      memory.register = { fileId: meta.id, modifiedTime: meta.modifiedTime, rows: sheets.REGISTER };
    }
  }

  memory.exists = Boolean(memory.map.fileId);
  if (!getState(memory, "mapping_state")) {
    setState(memory, "mapping_state", MAPPING_STATES.FIRST_MAPPING, new Date().toISOString());
  }
  if (org && !getState(memory, "org")) setState(memory, "org", org, new Date().toISOString());
  return memory;
}

export async function saveMemory(drive, memory) {
  const files = {
    map: await buildWorkbookBuffer({
      MAP: { columns: MAP_COLUMNS, rows: memory.map.sheets.MAP },
      RULES: { columns: RULES_COLUMNS, rows: memory.map.sheets.RULES },
      ROLES: { columns: ROLES_COLUMNS, rows: memory.map.sheets.ROLES },
      STATE: { columns: STATE_COLUMNS, rows: memory.map.sheets.STATE }
    }),
    register: await buildWorkbookBuffer({
      REGISTER: { columns: REGISTER_COLUMNS, rows: memory.register.rows }
    })
  };

  // Optimistic concurrency: if a memory file changed since it was loaded
  // (e.g. the owner edited it), abort instead of overwriting.
  for (const kind of ["map", "register"]) {
    const target = memory[kind];
    if (!target.fileId) continue;
    const meta = await drive.getMeta(target.fileId);
    if (meta.modifiedTime !== target.modifiedTime) {
      throw new Error(`MEMORY_CONFLICT: ${MEMORY_FILE_NAMES[kind]} changed since it was loaded`);
    }
  }

  for (const kind of ["map", "register"]) {
    const target = memory[kind];
    const result = target.fileId
      ? await drive.updateBinary(target.fileId, {
          buffer: files[kind],
          mimeType: XLSX_MIME,
          // Re-checked by the writer itself (bridge or direct): on mismatch
          // MEMORY_CONFLICT and nothing is written.
          expectedModifiedTime: target.modifiedTime
        })
      : await drive.createBinary({
          name: MEMORY_FILE_NAMES[kind],
          parentId: memory.memoryFolderId,
          buffer: files[kind],
          mimeType: XLSX_MIME
        });
    target.fileId = result.id;
    target.modifiedTime = result.modifiedTime || target.modifiedTime;
  }
  memory.exists = true;
  return { map_file_id: memory.map.fileId, register_file_id: memory.register.fileId };
}

export function getState(memory, key) {
  return memory.map.sheets.STATE.find(row => row.key === key)?.value || "";
}

export function setState(memory, key, value, now) {
  const row = memory.map.sheets.STATE.find(item => item.key === key);
  if (row) {
    row.value = String(value);
    row.updated_at = now;
  } else {
    memory.map.sheets.STATE.push({ key, value: String(value), updated_at: now });
  }
}

// ---------------------------------------------------------------------------
// Owner rules: signed, verifiable, never produced by the agent
// ---------------------------------------------------------------------------

function canonicalRule(rule) {
  return [
    rule.rule_id, rule.rule_type, rule.semantic_role, rule.target_file_id,
    rule.approval_source, rule.approved_by, rule.approved_at, String(rule.active)
  ].join("|");
}

export function signRule(rule, secret) {
  if (!secret) throw new Error("OWNER_APPROVAL_SECRET_MISSING");
  return createHmac("sha256", secret).update(canonicalRule(rule)).digest("hex");
}

export function verifyRule(rule, secret) {
  if (!secret || rule.approval_source !== "OWNER" || !rule.signature) return false;
  const expected = Buffer.from(signRule(rule, secret), "hex");
  const given = Buffer.from(String(rule.signature), "hex");
  return expected.length === given.length && timingSafeEqual(expected, given);
}

function activeValidRules(memory, secret, predicate) {
  return memory.map.sheets.RULES.filter(rule =>
    String(rule.active) === "true" && predicate(rule) && verifyRule(rule, secret)
  );
}

function unverifiedOwnerClaims(memory, secret, predicate) {
  return memory.map.sheets.RULES.filter(rule =>
    String(rule.active) === "true" && predicate(rule) && !verifyRule(rule, secret)
  );
}

// MAPPING_REVIEWED exists ONLY through an active owner-signed rule. A STATE
// cell edited by hand (or by anything else) claiming it is not trusted.
export function mappingState(memory, secret) {
  const reviewed = activeValidRules(memory, secret, rule => rule.rule_type === "MAPPING_REVIEWED");
  if (reviewed.length) return MAPPING_STATES.MAPPING_REVIEWED;
  const declared = getState(memory, "mapping_state") || MAPPING_STATES.FIRST_MAPPING;
  return declared === MAPPING_STATES.MAPPING_REVIEWED ? MAPPING_STATES.MAPPING_PENDING_REVIEW : declared;
}

// Business documentary actions start only once the owner reviewed the mapping.
export function documentaryActionsAllowed(memory, secret) {
  if (!memory?.exists) return { allowed: false, state: "NO_MAP", reason: "MAPPING_REQUIRED" };
  const state = mappingState(memory, secret);
  return state === MAPPING_STATES.MAPPING_REVIEWED
    ? { allowed: true, state }
    : { allowed: false, state, reason: "MAPPING_NOT_REVIEWED" };
}

function registerRow(memory, fileId) {
  return memory.register.rows.find(row => row.file_id === fileId) || null;
}

function ruleId(parts) {
  return `RULE-${sha256(parts.join("|")).slice(0, 12)}`;
}

function resign(rule, secret) {
  rule.signature = signRule(rule, secret);
}

// Owner actions — only called by api/owner.js (owner credential), never by a tool.
export function ownerApproveRole(memory, { semanticRole, targetFileId, approvedBy, secret, now, notes = "" }) {
  if (!secret) throw new Error("OWNER_APPROVAL_SECRET_MISSING");
  if (!SEMANTIC_ROLES[semanticRole]) throw new Error("UNKNOWN_SEMANTIC_ROLE");
  if (!String(approvedBy || "").trim()) throw new Error("APPROVER_REQUIRED");
  const target = registerRow(memory, targetFileId);
  if (!target || target.status !== "PRESENT") throw new Error("TARGET_NOT_IN_REGISTER");

  if (SEMANTIC_ROLES[semanticRole].cardinality === "SINGLE") {
    for (const rule of activeValidRules(memory, secret, r =>
      r.rule_type === "CANONICAL_ROLE_ASSIGNMENT" && r.semantic_role === semanticRole)) {
      rule.active = "false";
      rule.notes = `${rule.notes || ""} superseded ${now}`.trim();
      resign(rule, secret);
    }
  }

  const rule = {
    rule_id: ruleId([semanticRole, targetFileId, now]),
    rule_type: "CANONICAL_ROLE_ASSIGNMENT",
    semantic_role: semanticRole,
    target_file_id: targetFileId,
    target_name_at_approval: target.name,
    approval_source: "OWNER",
    approved_by: approvedBy,
    approved_at: now,
    active: "true",
    signature: "",
    notes
  };
  resign(rule, secret);
  memory.map.sheets.RULES.push(rule);

  let mapRow = memory.map.sheets.MAP.find(r => r.semantic_role === semanticRole && r.target_file_id === targetFileId);
  if (!mapRow) {
    mapRow = newMapRow(memory, { semanticRole, targetFileId, proposedBy: "OWNER", now, confidence: "1", rationale: "Owner assignment" });
    memory.map.sheets.MAP.push(mapRow);
  }
  mapRow.canonical_status = "OWNER_APPROVED";
  mapRow.owner_approval_status = "APPROVED";
  mapRow.rule_id = rule.rule_id;
  mapRow.last_verified_at = now;
  if (SEMANTIC_ROLES[semanticRole].cardinality === "SINGLE") {
    for (const other of memory.map.sheets.MAP) {
      if (other !== mapRow && other.semantic_role === semanticRole && other.canonical_status !== "REJECTED") {
        other.canonical_status = "SUPERSEDED";
      }
    }
  }
  return rule;
}

export function ownerRejectRole(memory, { semanticRole, targetFileId, approvedBy, secret, now, notes = "" }) {
  if (!secret) throw new Error("OWNER_APPROVAL_SECRET_MISSING");
  const rule = {
    rule_id: ruleId(["reject", semanticRole, targetFileId, now]),
    rule_type: "ROLE_REJECTION",
    semantic_role: semanticRole,
    target_file_id: targetFileId,
    target_name_at_approval: registerRow(memory, targetFileId)?.name || "",
    approval_source: "OWNER",
    approved_by: approvedBy,
    approved_at: now,
    active: "true",
    signature: "",
    notes
  };
  resign(rule, secret);
  memory.map.sheets.RULES.push(rule);
  for (const row of memory.map.sheets.MAP) {
    if (row.semantic_role === semanticRole && row.target_file_id === targetFileId) {
      row.canonical_status = "REJECTED";
      row.owner_approval_status = "REJECTED";
      row.rule_id = rule.rule_id;
    }
  }
  return rule;
}

export function ownerDeactivateRule(memory, { ruleIdToDeactivate, secret, now }) {
  const rule = memory.map.sheets.RULES.find(r => r.rule_id === ruleIdToDeactivate);
  if (!rule || !verifyRule(rule, secret)) throw new Error("RULE_NOT_FOUND_OR_UNVERIFIED");
  rule.active = "false";
  rule.notes = `${rule.notes || ""} deactivated ${now}`.trim();
  resign(rule, secret);
  return rule;
}

export function ownerMarkMappingReviewed(memory, { approvedBy, secret, now }) {
  if (!secret) throw new Error("OWNER_APPROVAL_SECRET_MISSING");
  const state = mappingState(memory, secret);
  if (state === MAPPING_STATES.FIRST_MAPPING) throw new Error("FIRST_MAPPING_NOT_COMPLETE");
  const rule = {
    rule_id: ruleId(["mapping-reviewed", now]),
    rule_type: "MAPPING_REVIEWED",
    semantic_role: "",
    target_file_id: "",
    target_name_at_approval: "",
    approval_source: "OWNER",
    approved_by: approvedBy,
    approved_at: now,
    active: "true",
    signature: "",
    notes: ""
  };
  resign(rule, secret);
  memory.map.sheets.RULES.push(rule);
  setState(memory, "mapping_state", MAPPING_STATES.MAPPING_REVIEWED, now);
  return rule;
}

// ---------------------------------------------------------------------------
// AI proposals (MAP hypotheses) and role resolution
// ---------------------------------------------------------------------------

function newMapRow(memory, { semanticRole, targetFileId, proposedBy, now, confidence, rationale }) {
  const target = registerRow(memory, targetFileId);
  return {
    map_id: `MAP-${sha256([semanticRole, targetFileId].join("|")).slice(0, 12)}`,
    org: getState(memory, "org"),
    semantic_role: semanticRole,
    target_file_id: targetFileId,
    target_kind: target?.is_folder === "true" ? "FOLDER" : "FILE",
    target_name: target?.name || "",
    target_path: target?.path || "",
    canonical_status: "AI_HYPOTHESIS",
    confidence: String(confidence ?? ""),
    rationale: String(rationale || "").slice(0, 1000),
    owner_approval_status: "PENDING",
    rule_id: "",
    proposed_by: proposedBy,
    proposed_at: now,
    last_verified_at: now,
    notes: ""
  };
}

// The AI may PROPOSE a role; it can never approve one.
export function proposeRole(memory, { semanticRole, targetFileId, confidence, rationale, now }) {
  if (!SEMANTIC_ROLES[semanticRole]) return { status: "UNKNOWN_SEMANTIC_ROLE" };
  const target = registerRow(memory, targetFileId);
  if (!target || target.status !== "PRESENT") return { status: "TARGET_NOT_IN_REGISTER" };
  const existing = memory.map.sheets.MAP.find(r => r.semantic_role === semanticRole && r.target_file_id === targetFileId);
  if (existing) {
    if (existing.canonical_status === "AI_HYPOTHESIS") {
      existing.confidence = String(confidence ?? existing.confidence);
      existing.rationale = String(rationale || existing.rationale).slice(0, 1000);
      existing.last_verified_at = now;
    }
    return { status: "ALREADY_MAPPED", map_row: existing };
  }
  const row = newMapRow(memory, { semanticRole, targetFileId, proposedBy: "AI", now, confidence, rationale });
  memory.map.sheets.MAP.push(row);
  return { status: "PROPOSED", map_row: row };
}

// resolve_semantic_role:
//   OWNER_APPROVED   -> use it (library_basis OWNER_APPROVED_MAP)
//   REVIEW_REQUIRED  -> concurrent owner rules for a SINGLE role, or approved target missing
//   NO_OWNER_APPROVAL-> no owner rule: normal discovery (hypotheses returned as hints)
export function resolveSemanticRole(memory, semanticRole, secret) {
  if (!SEMANTIC_ROLES[semanticRole]) return { status: "UNKNOWN_SEMANTIC_ROLE", semantic_role: semanticRole };
  const predicate = rule => rule.rule_type === "CANONICAL_ROLE_ASSIGNMENT" && rule.semantic_role === semanticRole;
  const valid = activeValidRules(memory, secret, predicate);
  const ignored = unverifiedOwnerClaims(memory, secret, predicate).map(rule => rule.rule_id);
  const hypotheses = memory.map.sheets.MAP
    .filter(row => row.semantic_role === semanticRole && row.canonical_status === "AI_HYPOTHESIS")
    .map(row => ({ target_file_id: row.target_file_id, target_name: row.target_name, target_path: row.target_path, confidence: row.confidence }));

  if (!valid.length) {
    return {
      status: "NO_OWNER_APPROVAL",
      semantic_role: semanticRole,
      hypotheses,
      ambiguous: SEMANTIC_ROLES[semanticRole].cardinality === "SINGLE" && hypotheses.length > 1,
      unverified_rules_ignored: ignored
    };
  }
  if (SEMANTIC_ROLES[semanticRole].cardinality === "SINGLE" && valid.length > 1) {
    return { status: "REVIEW_REQUIRED", reason: "CONCURRENT_OWNER_RULES", semantic_role: semanticRole, rule_ids: valid.map(r => r.rule_id) };
  }

  const targets = [];
  for (const rule of valid) {
    const row = registerRow(memory, rule.target_file_id);
    if (!row || row.status !== "PRESENT") {
      return { status: "REVIEW_REQUIRED", reason: "APPROVED_TARGET_MISSING", semantic_role: semanticRole, rule_id: rule.rule_id, target_file_id: rule.target_file_id, presence: row?.status || "UNKNOWN" };
    }
    targets.push({ target_file_id: row.file_id, name: row.name, path: row.path, rule_id: rule.rule_id, approved_by: rule.approved_by, approved_at: rule.approved_at });
  }
  return {
    status: "OWNER_APPROVED",
    basis: "OWNER_APPROVED_MAP",
    semantic_role: semanticRole,
    target_file_id: targets.length === 1 ? targets[0].target_file_id : null,
    targets,
    unverified_rules_ignored: ignored
  };
}

// ---------------------------------------------------------------------------
// Listing (Drive walk, or the existing orpailleur_inventory scanner)
// ---------------------------------------------------------------------------

export async function walkDrive(drive, rootFolderId, { maxItems = 20000, excludeIds = new Set() } = {}) {
  const items = [];
  const queue = [{ id: rootFolderId, path: "" }];
  let complete = true;
  while (queue.length) {
    const { id, path } = queue.shift();
    const children = await drive.listChildren(id);
    for (const child of children) {
      if (excludeIds.has(child.id)) continue;
      if (items.length >= maxItems) {
        complete = false;
        break;
      }
      const childPath = `${path}/${child.name}`;
      items.push({ ...child, parents: child.parents?.length ? child.parents : [id], path: childPath });
      if (child.mimeType === FOLDER_MIME) queue.push({ id: child.id, path: childPath });
    }
    if (!complete) break;
  }
  return { source: "DRIVE_WALK", items, complete };
}

// Rows of orpailleur_inventory seen by the latest scan run (existing durable
// scanner, reused as-is). complete=true only for a COMPLETE run.
export function listingFromInventory(rows, { runId, runStatus }) {
  const items = (rows || [])
    .filter(row => !runId || row.last_scan_id === runId)
    .map(row => ({
      id: row.file_id,
      name: row.name,
      mimeType: row.mime_type,
      parents: row.parent_id ? [row.parent_id] : [],
      modifiedTime: row.modified_at || "",
      size: row.size_bytes ?? "",
      webViewLink: row.web_url || "",
      version: row.drive_version || "",
      path: `${String(row.folder_path || "/").replace(/\/$/, "")}/${row.name}`
    }));
  return { source: "ORPAILLEUR_INVENTORY", items, complete: runStatus === "COMPLETE", run_id: runId || null };
}

// ---------------------------------------------------------------------------
// Differential pass
// ---------------------------------------------------------------------------

export function isSystemObject(item) {
  const name = String(item.name || "").trim().toLowerCase();
  if (item.mimeType === FOLDER_MIME) return SYSTEM_FOLDER_PATTERN.test(name);
  return SYSTEM_FILE_PATTERN.test(name);
}

function isMemoryFile(item) {
  return Object.values(MEMORY_FILE_NAMES).includes(item.name);
}

export function classifyChange(previous, item) {
  if (!previous) return ["NEW"];
  const types = [];
  const contentChanged =
    String(previous.modified_time || "") !== String(item.modifiedTime || "") ||
    String(previous.size || "") !== String(item.size ?? "") ||
    (item.md5Checksum && String(previous.md5 || "") !== String(item.md5Checksum));
  if (item.mimeType !== FOLDER_MIME && contentChanged) types.push("MODIFIED");
  if (previous.name !== item.name) types.push("RENAMED");
  if (String(previous.parent_id || "") !== String(item.parents?.[0] || "")) types.push("MOVED");
  return types.length ? types : ["UNCHANGED"];
}

function emptyRegisterRow() {
  return Object.fromEntries(REGISTER_COLUMNS.map(column => [column, ""]));
}

export async function runMappingPass(drive, {
  memoryFolderId,
  rootFolderId,
  listing = null,
  maxReads = 150,
  maxItems = 20000,
  readChars = 30000,
  now = new Date(),
  org = ""
}) {
  const nowIso = now.toISOString();
  const memory = await openMemory(drive, { memoryFolderId, org });
  const memoryIds = new Set([memory.map.fileId, memory.register.fileId].filter(Boolean));
  const current = listing || await walkDrive(drive, rootFolderId, { maxItems, excludeIds: memoryIds });

  const previousById = new Map(memory.register.rows.map(row => [row.file_id, row]));
  const seen = new Set();
  const counts = Object.fromEntries([...CHANGE_TYPES, "MISSING_PENDING_CHECK", "MOVED_OUT_OF_SCOPE", "TRASHED", "REAPPEARED"].map(t => [t, 0]));
  const toRead = [];

  for (const item of current.items) {
    if (memoryIds.has(item.id)) continue;
    seen.add(item.id);
    const previous = previousById.get(item.id);
    const types = classifyChange(previous, item);
    const row = previous || emptyRegisterRow();
    const wasAbsent = previous && previous.status && previous.status !== "PRESENT";

    Object.assign(row, {
      file_id: item.id,
      parent_id: item.parents?.[0] || "",
      name: item.name,
      path: item.path || row.path || "",
      mime_type: item.mimeType,
      size: String(item.size ?? ""),
      modified_time: item.modifiedTime || "",
      created_time: item.createdTime || row.created_time || "",
      md5: item.md5Checksum || row.md5 || "",
      web_url: item.webViewLink || row.web_url || "",
      is_folder: item.mimeType === FOLDER_MIME ? "true" : "false",
      first_seen_at: row.first_seen_at || nowIso,
      last_seen_at: nowIso,
      status: "PRESENT",
      change_type: types.join("+"),
      missing_since: "",
      missing_checks: "0"
    });
    if (!previous) memory.register.rows.push(row);
    for (const type of types) counts[type] += 1;
    if (wasAbsent) counts.REAPPEARED += 1;

    const changed = !types.includes("UNCHANGED");
    if (isMemoryFile(item)) {
      row.semantic_role = "OFFICE_MANAGER_MEMORY";
      row.understanding_status = "METADATA_ONLY";
      row.read_status = "SKIPPED_SYSTEM";
      continue;
    }
    if (isSystemObject(item)) {
      row.understanding_status = "METADATA_ONLY";
      row.read_status = "SKIPPED_SYSTEM";
      continue;
    }
    if (row.is_folder === "true") {
      // Folders are understood by the AI from their name, place and children.
      if (changed || !row.understanding_status) row.understanding_status = "NEEDS_UNDERSTANDING";
      continue;
    }
    if (changed || row.understanding_status === "PENDING_READ" || !row.understanding_status) {
      row.understanding_status = "PENDING_READ";
      row._renamedOrMoved = types.includes("RENAMED") || types.includes("MOVED") || types.includes("NEW");
      toRead.push(row);
    }
  }

  // Absent objects: never concluded deleted on first absence.
  if (current.complete) {
    for (const row of memory.register.rows) {
      if (seen.has(row.file_id) || memoryIds.has(row.file_id)) continue;
      if (["DELETED_OR_MISSING", "TRASHED"].includes(row.status)) continue;
      const meta = await drive.getMeta(row.file_id).catch(() => null);
      if (meta && meta.trashed) {
        row.status = "TRASHED";
        row.change_type = "TRASHED";
        counts.TRASHED += 1;
      } else if (meta) {
        row.status = "MOVED_OUT_OF_SCOPE";
        row.parent_id = meta.parents?.[0] || row.parent_id;
        row.name = meta.name || row.name;
        row.change_type = "MOVED";
        counts.MOVED_OUT_OF_SCOPE += 1;
      } else {
        const checks = Number(row.missing_checks || 0) + 1;
        row.missing_checks = String(checks);
        row.missing_since = row.missing_since || nowIso;
        if (checks >= MISSING_CONFIRMATION_PASSES) {
          row.status = "DELETED_OR_MISSING";
          row.change_type = "DELETED_OR_MISSING";
          counts.DELETED_OR_MISSING += 1;
        } else {
          row.status = "MISSING_PENDING_CHECK";
          row.change_type = "MISSING_PENDING_CHECK";
          counts.MISSING_PENDING_CHECK += 1;
        }
      }
      row.last_action = `PRESENCE_CHECK_${row.status}`;
      row.last_action_at = nowIso;
    }
  }

  // Open + read changed business files (bounded); UNCHANGED files are never re-read.
  let readsDone = 0;
  for (const row of toRead) {
    const renamedOrMoved = row._renamedOrMoved;
    delete row._renamedOrMoved;
    if (!READABLE_MIMES.has(row.mime_type) && !String(row.mime_type).startsWith("text/")) {
      row.read_status = "EXTRACTOR_REQUIRED";
      row.understanding_status = "EXTRACTOR_REQUIRED";
      continue;
    }
    if (readsDone >= maxReads) continue; // stays PENDING_READ for the next pass
    readsDone += 1;
    const read = await drive.readText(row.file_id, { maxChars: readChars })
      .catch(error => ({ supported: false, reason: error.message }));
    row.last_inspected_at = nowIso;
    if (!read.supported) {
      row.read_status = "EXTRACTOR_REQUIRED";
      row.understanding_status = "EXTRACTOR_REQUIRED";
      continue;
    }
    const fingerprint = contentFingerprint(read.file || { id: row.file_id, modifiedTime: row.modified_time }, read.text);
    const sameContent = row.content_fingerprint && row.content_fingerprint === fingerprint;
    row.content_fingerprint = fingerprint;
    row.read_status = "READ";
    row.understanding_status =
      sameContent && !renamedOrMoved && row.semantic_role ? "UNDERSTOOD" : "NEEDS_UNDERSTANDING";
    row.last_action = "READ";
    row.last_action_at = nowIso;
  }
  for (const row of toRead) delete row._renamedOrMoved;

  // MAP follows roles, not paths: refresh names/paths of mapped targets.
  for (const mapRow of memory.map.sheets.MAP) {
    const target = registerRow(memory, mapRow.target_file_id);
    if (!target) continue;
    mapRow.target_name = target.name;
    mapRow.target_path = target.path;
    mapRow.last_verified_at = nowIso;
    if (target.status !== "PRESENT" && mapRow.canonical_status !== "REJECTED") {
      mapRow.notes = `target ${target.status} at ${nowIso}`;
    }
  }

  const previousState = getState(memory, "mapping_state") || MAPPING_STATES.FIRST_MAPPING;
  if (previousState === MAPPING_STATES.FIRST_MAPPING && current.complete) {
    setState(memory, "mapping_state", MAPPING_STATES.MAPPING_PENDING_REVIEW, nowIso);
  }
  const scanCount = Number(getState(memory, "scan_count") || 0) + 1;
  setState(memory, "scan_count", scanCount, nowIso);
  setState(memory, "last_scan_at", nowIso, nowIso);
  setState(memory, "last_scan_complete", current.complete ? "true" : "false", nowIso);
  setState(memory, "last_listing_source", current.source, nowIso);
  setState(memory, "last_pass_summary", JSON.stringify(counts), nowIso);

  const saved = await saveMemory(drive, memory);

  const pendingReads = memory.register.rows.filter(r => r.understanding_status === "PENDING_READ").length;
  const needsUnderstanding = memory.register.rows.filter(r => r.understanding_status === "NEEDS_UNDERSTANDING").length;
  return {
    memory,
    summary: {
      pass_mode: scanCount === 1 ? "FIRST_MAPPING" : "DIFFERENTIAL",
      mapping_state: getState(memory, "mapping_state"),
      listing_source: current.source,
      listing_complete: current.complete,
      objects_seen: seen.size,
      counts,
      reads_done: readsDone,
      pending_reads: pendingReads,
      needs_understanding: needsUnderstanding,
      business_actions_performed: 0,
      ...saved
    }
  };
}

// ---------------------------------------------------------------------------
// AI understanding (recorded, never generated here)
// ---------------------------------------------------------------------------

export function recordUnderstanding(memory, items, { now }) {
  const results = [];
  for (const item of items) {
    const row = registerRow(memory, item.file_id);
    if (!row) {
      results.push({ file_id: item.file_id, status: "NOT_IN_REGISTER" });
      continue;
    }
    if (!SEMANTIC_ROLES[item.semantic_role]) {
      results.push({ file_id: item.file_id, status: "UNKNOWN_SEMANTIC_ROLE" });
      continue;
    }
    if (row.is_folder !== "true") {
      if (row.read_status !== "READ") {
        results.push({ file_id: item.file_id, status: "NOT_READ_YET" });
        continue;
      }
      if (item.content_fingerprint !== row.content_fingerprint) {
        results.push({ file_id: item.file_id, status: "STALE_FINGERPRINT" });
        continue;
      }
    }
    Object.assign(row, {
      semantic_role: item.semantic_role,
      classification: String(item.classification || "").slice(0, 120),
      client: String(item.client || "").slice(0, 120),
      mission: String(item.mission || "").slice(0, 120),
      understanding_status: "UNDERSTOOD",
      understanding_confidence: String(item.confidence ?? ""),
      understanding_rationale: String(item.rationale || "").slice(0, 800),
      last_action: "UNDERSTOOD_BY_AI",
      last_action_at: now
    });
    results.push({ file_id: item.file_id, status: "RECORDED" });
  }
  return results;
}

// ---------------------------------------------------------------------------
// Owner report: how the AI understood the organisation + what needs validation
// ---------------------------------------------------------------------------

export function buildMappingReport(memory, secret) {
  const rows = memory.register.rows;
  const byRole = {};
  for (const row of rows) {
    if (row.status !== "PRESENT") continue;
    const role = row.semantic_role || "UNKNOWN";
    byRole[role] = (byRole[role] || 0) + 1;
  }
  const roles = SEMANTIC_ROLE_KEYS.map(role => ({ role, resolution: resolveSemanticRole(memory, role, secret) }));
  const questions = [];
  for (const { role, resolution } of roles) {
    if (SEMANTIC_ROLES[role].cardinality !== "SINGLE" || role === "OFFICE_MANAGER_MEMORY") continue;
    if (resolution.status === "REVIEW_REQUIRED") {
      questions.push({ semantic_role: role, question: "REVIEW_REQUIRED", detail: resolution });
    } else if (resolution.status === "NO_OWNER_APPROVAL" && resolution.hypotheses.length) {
      questions.push({
        semantic_role: role,
        question: resolution.hypotheses.length > 1 ? "WHICH_ONE_IS_CANONICAL" : "CONFIRM_CANONICAL",
        candidates: resolution.hypotheses
      });
    }
  }
  return {
    mapping_state: mappingState(memory, secret),
    scan_count: Number(getState(memory, "scan_count") || 0),
    last_scan_at: getState(memory, "last_scan_at"),
    last_scan_complete: getState(memory, "last_scan_complete") === "true",
    objects: {
      total: rows.length,
      present: rows.filter(r => r.status === "PRESENT").length,
      folders: rows.filter(r => r.is_folder === "true" && r.status === "PRESENT").length,
      pending_read: rows.filter(r => r.understanding_status === "PENDING_READ").length,
      needs_understanding: rows.filter(r => r.understanding_status === "NEEDS_UNDERSTANDING").length,
      understood: rows.filter(r => r.understanding_status === "UNDERSTOOD").length,
      extractor_required: rows.filter(r => r.understanding_status === "EXTRACTOR_REQUIRED").length,
      missing_pending_check: rows.filter(r => r.status === "MISSING_PENDING_CHECK").length
    },
    objects_by_role: byRole,
    roles: roles.map(({ role, resolution }) => ({ role, status: resolution.status, targets: resolution.targets || [], hypotheses: resolution.hypotheses || [] })),
    owner_questions: questions
  };
}
